"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Image from "next/image";

// Sample Data (Baad mein ye Firebase se aayega)
const WALLPAPERS = [
  { id: 1, title: "Golden Ether", category: "Abstract", url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe" },
    { id: 2, title: "Noir Marble", category: "Textures", url: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853" },
      { id: 3, title: "Champagne Velvet", category: "Luxury", url: "https://images.unsplash.com/photo-1502691876148-a84978e59af8" },
        { id: 4, title: "Ivory Flow", category: "Minimal", url: "https://images.unsplash.com/photo-1557683316-973673baf926" },
          { id: 5, title: "Royal Essence", category: "Premium", url: "https://images.unsplash.com/photo-1614850523296-d8c1af93d400" },
            { id: 6, title: "Liquid Gold", category: "Abstract", url: "https://images.unsplash.com/photo-1604871000636-074fa5117945" },
            ];

            export default function WallpaperGallery() {
              const [hoveredId, setHoveredId] = useState<number | null>(null);

                return (
                    <main className="min-h-screen bg-executive-black text-soft-ivory selection:bg-champagne-gold selection:text-executive-black">
                          
                                {/* 1. Header Section */}
                                      <section className="py-24 px-4 max-w-7xl mx-auto text-center">
                                              <motion.div
                                                        initial={{ opacity: 0, y: 20 }}
                                                                  animate={{ opacity: 1, y: 0 }}
                                                                            transition={{ duration: 0.8 }}
                                                                                    >
                                                                                              <span className="text-champagne-gold tracking-[0.5em] uppercase text-xs mb-4 block font-medium">
                                                                                                          The Gallery
                                                                                                                    </span>
                                                                                                                              <h1 className="text-4xl font-serif mb-6 sm:text-5xl md:text-6xl">Masterpieces</h1>
                                                                                                                                        <div className="h-[1px] w-24 bg-champagne-gold mx-auto opacity-50" />
                                                                                                                                                </motion.div>
                                                                                                                                                      </section>

                                                                                                                                                            {/* 2. Gallery Grid */}
                                                                                                                                                                  <section className="max-w-[1400px] mx-auto px-4 pb-20">
                                                                                                                                                                          <div className="columns-1 md:columns-2 lg:columns-3 gap-8 space-y-8">
                                                                                                                                                                                    {WALLPAPERS.map((wp) => (
                                                                                                                                                                                                <motion.div
                                                                                                                                                                                                              key={wp.id}
                                                                                                                                                                                                                            className="relative break-inside-avoid group cursor-none"
                                                                                                                                                                                                                                          onMouseEnter={() => setHoveredId(wp.id)}
                                                                                                                                                                                                                                                        onMouseLeave={() => setHoveredId(null)}
                                                                                                                                                                                                                                                                      initial={{ opacity: 0 }}
                                                                                                                                                                                                                                                                                    whileInView={{ opacity: 1 }}
                                                                                                                                                                                                                                                                                                  viewport={{ once: true }}
                                                                                                                                                                                                                                                                                                                data-hover
                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                            {/* Image Container */}
                                                                                                                                                                                                                                                                                                                                          <div className="relative overflow-hidden rounded-sm border border-soft-ivory/5">
                                                                                                                                                                                                                                                                                                                                                          <Image
                                                                                                                                                                                                                                                                                                                                                                            src={wp.url}
                                                                                                                                                                                                                                                                                                                                                                                              alt={wp.title}
                                                                                                                                                                                                                                                                                                                                                                                                                width={600}
                                                                                                                                                                                                                                                                                                                                                                                                                                  height={800}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full object-cover transition-transform duration-[1.5s] ease-out group-hover:scale-110"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Glassmorphic Overlay on Hover */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {hoveredId === wp.id && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                initial={{ opacity: 0, y: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            exit={{ opacity: 0, y: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="absolute inset-x-4 bottom-4 p-6 bg-executive-black/40 backdrop-blur-xl border border-soft-ivory/10 z-20"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-champagne-gold text-[10px] tracking-widest uppercase mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {wp.category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-xl font-serif text-soft-ivory tracking-wide">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {wp.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="mt-4 text-[10px] uppercase tracking-widest border-b border-champagne-gold pb-1 hover:text-champagne-gold transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            View Details
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </AnimatePresence>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Subtle Dark Gradient Overlay */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="absolute inset-0 bg-gradient-to-t from-executive-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
